export const portfolioData = {
  name: "Sushila Neupane",
  title: "Full Stack Developer",
  location: "Kathmandu, Nepal",
  email: "sushilaneupane2001@gmail.com",
  phone: "9863476766",
  bio: "Motivated and detail-oriented final-year B.Sc. CSIT student passionate about full-stack web development. Skilled in building responsive UIs, scalable APIs, reusable components, and real-world applications using JavaScript, TypeScript, and modern frameworks.",
  social: {
    github: "https://github.com/sushilaneupane",
    linkedin: "https://www.linkedin.com/in/sushila-neupane-039b55282/",
    email: "sushilaneupane2001@gmail.com",
  },
  education: [
    {
      school: "Padma Kanya Multiple Campus",
      degree: "B.Sc. CSIT",
      period: "2022–Present",
      university: "Tribhuvan University",
    },
    {
      school: "Liverpool International College",
      degree: "NEB (+2 Science)",
      period: "2018–2020",
      location: "Kathmandu",
    },
    {
      school: "Janata Mavi School",
      degree: "SEE",
      period: "2007–2017",
      location: "Bagdula, Pyuthan",
    },
  ],
  experience: [
    {
      company: "Silicon Soft & IT Consultant",
      position: "Full Stack Developer",
      duration: "4 Months",
      durationInMonths: "3 Months",
      responsibilities: [
        "Designed and developed professional CV/Resume UI using HTML, CSS, and React.js",
        "Built a functional To-Do App using React.js with smooth UI and local state management",
        "Developed a complete E-commerce Website including product UI, filtering, search, and API integration",
        "Contributed to an Attendance Management System using TypeScript, improving validation, type safety & structure",
        "Worked collaboratively using Git, GitHub, and followed real-world coding standards and best practices",
        "Participated in full-stack development lifecycle from design to deployment",
      ],
    },
  ],
  skills: {
    frontend: ["HTML", "CSS", "JavaScript", "React.js", "Next.js", "Tailwind CSS", "shadcn/ui", "Bootstrap"],
    backend: ["Node.js", "Express.js"],
    database: ["MySQL"],
    tools: ["Git", "GitHub", "VS Code", "Postman"],
    other: ["REST APIs", "JWT Auth", "Multer", "TypeScript"],
  },
  projects: [
    {
      id: 1,
      title: "Personal Portfolio Website",
      description:
        "A fully responsive website created to showcase my skills, education, and projects with clean and modern UI.",
      github: "https://github.com/sushilaneupane/personal-website",
      technologies: ["Next.js", "shadcn/ui", "tailwindcss", "Responsive Design"],
      keyFeatures: [
        "Designed a clean and modern UI using HTML, CSS, and Bootstrap",
        "Implemented responsive grid layouts for mobile, tablet, and desktop",
        "Added smooth navigation and project cards for better user experience",
      ],
    },
    {
      id: 2,
      title: "To-Do App",
      description: "A task-management app created during internship with intuitive UI and full CRUD operations.",
      github: "https://github.com/sushilaneupane/TO-DO-APP",
      technologies: ["React.js", "JavaScript", "State Management"],
      keyFeatures: [
        "Built using React.js with controlled input fields",
        "Implemented add, edit, delete, and complete task features",
        "Managed data using useState for fast updates",
      ],
    },
    {
      id: 3,
      title: "E-commerce Backend",
      description: "A backend system for an e-commerce platform with secure REST APIs and MySQL database structure.",
      github: "https://github.com/sushilaneupane/ecommerce-backend",
      technologies: ["Node.js", "Express.js", "MySQL", "JWT", "Multer"],
      keyFeatures: [
        "Built secure REST APIs using Node.js and Express.js",
        "Designed scalable MySQL database structure for users, products, categories, cart, wishlist, payment & orders",
        "Implemented JWT authentication for secure login/register",
        "Integrated Multer for handling product image uploads",
        "Focused on validation, middleware, routing, and security",
      ],
    },
    {
      id: 4,
      title: "E-commerce Frontend",
      description:
        "A full responsive frontend interface for an e-commerce platform with modern UI and smooth interactions.",
      github: "https://github.com/sushilaneupane/ecommerce-frontend",
      technologies: ["React.js", "shadcn/ui", "tailwindcss", "react-query", "Axios"],
      keyFeatures: [
        "Designed UI using React.js, Bootstrap, and custom CSS",
        "Implemented products page, cart page, and product details page",
        "Fetched backend APIs using Axios for dynamic content",
        "Added loading states, error handling, and cleaner UI interactions",
      ],
    },
    {
      id: 5,
      title: "Attendance Management System",
      description: "A real-world attendance handling system built with TypeScript for strict type safety.",
      github: "https://github.com/sushilaneupane/attendanceSystem",
      technologies: ["React", "TypeScript", "API Integration", "Validation"],
      keyFeatures: [
        "Used TypeScript for strict type safety and fewer runtime errors",
        "Designed UI screens with React + TypeScript",
        "Implemented API integration and proper validation",
        "Enhanced component structure for scalability and maintainability",
        "Followed best practices for interfaces, types, and reusable components",
      ],
    },
    {
      id: 6,
      title: "React Resume",
      description: "A professional resume builder created with React.js and Tailwind CSS for modern styling.",
      github: "https://github.com/sushilaneupane/React_resume",
      technologies: ["React.js", "Tailwind CSS", "JavaScript"],
      keyFeatures: [
        "Built a responsive resume template using React and Tailwind CSS",
        "Implemented dynamic content rendering for resume sections",
        "Created reusable components for different resume sections",
        "Focused on modern UI design and responsive layouts",
      ],
    },
    {
      id: 7,
      title: "Tic Tac Toe Game",
      description:
        "A classic tic-tac-toe game built with React.js featuring interactive gameplay and game state management.",
      github: "https://github.com/sushilaneupane/tic-tac-toe",
      technologies: ["React.js", "JavaScript", "Game Logic"],
      keyFeatures: [
        "Implemented game logic with win detection and draw handling",
        "Built interactive UI with click handlers and state management",
        "Added game reset functionality and turn tracking",
        "Created a playable two-player game experience",
      ],
    },
    {
      id: 8,
      title: "React Calculator",
      description: "A functional calculator application built with React.js supporting basic arithmetic operations.",
      github: "https://github.com/sushilaneupane/React-calculator",
      technologies: ["React.js", "JavaScript", "State Management"],
      keyFeatures: [
        "Built calculator UI with responsive button layout",
        "Implemented arithmetic operations (add, subtract, multiply, divide)",
        "Managed calculator state using React hooks",
        "Added clear and reset functionality",
      ],
    },
    {
      id: 9,
      title: "Resume Website",
      description: "A pure HTML and CSS resume website showcasing a clean and professional design.",
      github: "https://github.com/sushilaneupane/Resume",
      technologies: ["HTML", "CSS", "Semantic HTML"],
      keyFeatures: [
        "Created a professional resume using pure HTML and CSS",
        "Implemented semantic HTML for better structure and accessibility",
        "Designed responsive typography and spacing",
        "Focused on clean, minimalist design principles",
      ],
    },
    {
      id: 10,
      title: "CH8R",
      description: "A collaborative web project showcasing HTML and CSS skills with modern design elements.",
      github: "https://github.com/sushilaneupane/CH8R",
      technologies: ["HTML", "CSS", "Web Design"],
      keyFeatures: [
        "Built web pages using semantic HTML structure",
        "Implemented responsive CSS styling and layouts",
        "Created modern design elements and navigation",
        "Focused on user experience and visual hierarchy",
      ],
    },
  ],
  languages: ["Nepali", "English"],
}
